#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_MAIN_ICON                           100
#define IDR_MAIN_MENU                           200
#define IDD_TRANSFORMACIONES                    300
#define IDD_MATRIZ_ARBITRARIA                   302
#define IDD_PROP_OBJETO                         304
#define IDD_PROP_LUZ                            306
#define IDD_AYUDA_CONTROLES                     308
#define IDC_MA_V00                              1001
#define IDC_POBJ_REFLECTION                     1001
#define IDC_MA_IDENTIDAD                        1002
#define IDC_POBJ_COLOR                          1002
#define IDC_PLUZ_COLOR                          1005
#define IDC_PLUZ_CAMBIARCOLOR                   1006
#define IDM_CARGAR_OBJETO                       40000
#define IDM_SALIR                               40001
#define IDM_INDICADOR_DE_CENTRO                 40002
#define IDM_INDICADOR_DE_LUZ                    40003
#define IDM_PHONG_SHADING                       40004
#define IDC_TAPPER_ATRAS                        40005
#define IDM_TRANSFORMACIONES                    40005
#define IDM_MATRIZ_ARBITRARIA                   40006
#define IDC_TAPPER_ARRIBA                       40007
#define IDM_PROP_LUZ                            40007
#define IDM_PROP_OBJETO                         40008
#define IDC_TAPPER_ADELANTE                     40009
#define IDM_TODO                                40009
#define IDM_OBJETO                              40010
#define IDC_TAPPER_IZQUIERDA                    40011
#define IDM_LUZ                                 40011
#define IDM_MATRIZ_DEL_OBJETO                   40012
#define IDC_TAPPER_ABAJO                        40013
#define IDM_PROPIEDADES_DEL_OBJETO              40013
#define IDM_MATRIZ_DE_LA_LUZ                    40014
#define IDC_TAPPER_DERECHA                      40015
#define IDM_PROPIEDADES_DE_LA_LUZ               40015
#define IDM_CONTROLES                           40016
#define IDC_TAPPER_SLIDER                       40017
#define IDC_TAPPER_VALUE                        40019
#define IDC_TWIST_ATRAS                         40021
#define IDC_TWIST_ARRIBA                        40023
#define IDC_TWIST_ADELANTE                      40025
#define IDC_TWIST_IZQUIERDA                     40027
#define IDC_TWIST_ABAJO                         40029
#define IDC_TWIST_DERECHA                       40031
#define IDC_TWIST_SLIDER                        40033
#define IDC_TWIST_VALUE                         40035
#define IDC_MA_V01                              40051
#define IDC_MA_V02                              40052
#define IDC_MA_V03                              40053
#define IDC_MA_V22                              40054
#define IDC_MA_V23                              40055
#define IDC_MA_V30                              40058
#define IDC_MA_V31                              40059
#define IDC_MA_V32                              40060
#define IDC_MA_V33                              40061
#define IDC_MA_V10                              40062
#define IDC_MA_V11                              40063
#define IDC_MA_V12                              40064
#define IDC_MA_V13                              40065
#define IDC_MA_V20                              40066
#define IDC_MA_V21                              40067
#define IDC_MA_APLICAR                          40068
#define IDC_TNL_RESTAURAR                       40069
#define IDC_POBJ_GRPLIST                        40073
#define IDC_POBJ_CTRIANGULOS                    40075
#define IDC_POBJ_CAMBIARCOLOR                   40076
#define IDC_PLUZ_AMBIENCE                       40078
#define IDC_POBJ_REFSLIDER                      40078
#define IDC_PLUZ_AMBSLIDER                      40079
